---
- name: Install certbot via snap
  snap:
    name: certbot
    classic: yes
  tags: 
  - installation
  - certbot
  - everythingbutmoodle
- name: Make Symlink for Certbot
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

