---
- name: Setup cronjob to run each minute
  cron:
    name: Moodle Cron Job - {{ moodle_domain }}
    user: www-data
    job: "php /srv/{{ app_name }}/www/admin/cli/cron.php > /dev/null 2>&1"
    disabled: "{{ disable_cron }}"

