---
- name: Configuracion del Moodle directory
  file:
    path: /srv/{{ app_name }}
    state: directory
    mode: "0755"
    owner: "{{ non_root_user }}"
    group: "{{ non_root_user }}"


- name: Configuracion del Moodledata directory /srv/{{ app_name }}/moodledata
  file:
    path: /srv/{{ app_name }}/moodledata
    state: directory
    owner: www-data
    group: www-data
    mode: "0700"
- name: Delete moodle code folder
  ansible.builtin.file:
    state: absent
    path: /srv/{{ app_name }}/www/
- name: Clone Moodle en /srv/{{ app_name }}/www
  git:
    repo: https://github.com/moodle/moodle.git
    dest: /srv/{{ app_name }}/www/
    clone: true
    version: "{{ moodle_git_branch }}"
    depth: 1

- name: Cambiar el ownership recursivamente el directorio de Moodle
  file:
    path: /srv/{{ app_name }}/www
    state: directory
    recurse: yes
    owner: www-data
    group: "{{ non_root_user }}"

- name: configurar config.php para moodle
  template:
    dest: "/srv/{{ app_name }}/www/config.php"
    mode: "0444"
    owner: www-data
    group: www-data
    src: templates/config.php.j2

