---
- name: Configurar Nginx Virtualhost
  template:
    dest: "/etc/nginx/sites-available/{{ moodle_domain }}"
    mode: "0664"
    src: templates/vhost.j2
  
- name: Adicionar Symlink para el  Nginx Virtualhost
  file:
    src: "/etc/nginx/sites-available/{{ moodle_domain }}"
    dest: "/etc/nginx/sites-enabled/{{ moodle_domain }}"
    state: link

- name: Eliminar el sitio por defecto de nginx
  file:
    name: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Reiniciar Nginx 
  service:
    name: nginx
    state: restarted

