---
- name: Cambiar post_max_size en php.ini
  ini_file:
    path: /etc/php/{{ php_version }}/fpm/php.ini
    section: PHP
    option: post_max_size
    value: "{{ max_uploadable_filesize }}"
  
- name: Cambiar upload_max_filesize en php.ini
  ini_file:
    path: /etc/php/{{ php_version }}/fpm/php.ini
    section: PHP
    option: upload_max_filesize
    value: "{{ max_uploadable_filesize }}"
  
- name: Cambiar max_input_time en php.ini
  ini_file:
    path: /etc/php/{{ php_version }}/fpm/php.ini
    section: PHP
    option: max_input_time
    value: 600

- name: Cambiar max_execution_time en php.ini
  ini_file:
    path: /etc/php/{{ php_version }}/fpm/php.ini
    section: PHP
    option: max_execution_time
    value: 300

- name: Cambiar memory_limit en php.ini
  ini_file:
    path: /etc/php/{{ php_version }}/fpm/php.ini
    section: PHP
    option: memory_limit
    value: 256M
  
- name: Cambiar max_input_vars en php.ini
  ini_file:
    path: /etc/php/{{ php_version }}/fpm/php.ini
    section: PHP
    option: max_input_vars
    value: 10000
  
- name: Reiniciar php{{ php_version }}-fpm 
  service:
    name: php{{ php_version }}-fpm
    state: restarted

