---
- name: Instalando plugin certificate
  git:
    repo: https://github.com/mdjnelson/moodle-mod_customcert.git
    dest: "/srv/{{ app_name }}/www/mod/customcert"
    version: "{{ moodle_git_branch }}"
    clone: true
    depth: 1
- name: Instalando plugin Zoom
  git:
    repo: https://github.com/ncstate-delta/moodle-mod_zoom.git
    dest: "/srv/{{ app_name }}/www/mod/zoom"
    version: "main"
    clone: true
    depth: 1
- name: Instalando plugin test email
  git:
    repo: https://github.com/michael-milette/moodle-local_mailtest.git
    dest: "/srv/{{ app_name }}/www/local/mailtest"
    version: "master"
    clone: true
    depth: 1
- name: Instalando plugin de reporte
  git:
    repo: https://github.com/ewallah/moodle-report_growth.git
    dest: "/srv/{{ app_name }}/www/report/growth"
    version: "main"
    clone: true
    depth: 1
# No probdo en la version 4.2
#- name: Instalando plugin jazzquiz 
#  git:
#    repo: https://github.com/KQMATH/moodle-mod_jazzquiz.git
#    dest: "/srv/{{ app_name }}/www/mod/jazzquiz"
#    version: "main"
#    clone: true
#    depth: 1

