---
#- name: Add Postgres user
#  command: sudo -u postgres psql -c "CREATE USER {{ db_user }} WITH PASSWORD '{{ db_pass }}';"  

#- name: Add Postgres Database
#  command: sudo -u postgres createdb -O {{ db_user }} {{ db_name }}

- name: "Creacion de la base de datos"
  postgresql_db:
    state: present
    name: "{{ db_name }}"
  become: yes
  become_user: postgres

- name: "Creacion del usuario de la base de datos"
  postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
  become: yes
  become_user: postgres

- name: "Dar acceso al usuairo a la base de datos"
  postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    grant_option: no
    privs: all
  become: yes
  become_user: postgres
#- name: "Permitir acceso a la base de datos desde otro servidor"
#  postgresql_pg_hba:
#    dest: "/etc/postgresql/13/main/pg_hba.conf"
#    contype: host
#    databases: all
#    method: md5
#    users: "{{ db_user }}"
#    create: true
#  become: yes
#  become_user: postgres
#  notify: restart postgres

#handlers:
#- name: restart postgres
#  service: name=postgresql state=restarted 
